config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :tasks
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper 
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
 #ログインしていなければトップページ(tasks/index.html.erb)に戻す
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:seccess] = 'ログインに成功しました'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  #params[:session][:---]で送られてきた値を二つのパラメーターに代入する

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  #session[:user_id]をnilにすることでログアウト
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  #emailとpasswordがあっていれば
  # session[:user_id] = @user.id が代入されればログイン成功
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  #ログインしていなければトップページへ戻る
  before_action :correct_user, only: [:destroy, :update, :show, :edit]
  #ログイン中のユーザーの自分のタスク以外ならトップページ戻る
  
  def index
    @tasks = current_user.tasks.order(id: :desc).page(params[:page])
  end
  #ログインしていれば、@tasksインスタンスを生成
  
  def show
  end
  
  def new
    @task = current_user.tasks.build
  end
  #@task= Task.new(user: user)のこと
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'Taskが正常に投稿されました'
      redirect_to root_url
    else
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'Taskが投稿されませんでした'
      render :new
    end
  end
  
  def edit
  end
  #取り扱い中のタスクのインスタンス　updateにcorrect_userを適応しているからOK
  
  def update
    if @task.update(task_params)
      flash[:success] = 'Taskは正常に更新されました'
      redirect_to root_url
    else
      flash.now[:danger] = 'Taskは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = 'Taskは正常に削除されました'
    redirect_to root_url
  end
  #correct_userの中に@taskインスタンスがあるため@task=は省略
  
  private 
  
  
  def correct_user
    #@task = current_user.tasks.find_by(id: params[:id])
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_path
    end
  end
  #@task=表示中（取り扱い中）のtask.idがログインユーザのtasksから検索
  #もし違えばトップページに戻る（タスク一覧）
  
  def task_params
   params.require(:task).permit(:content, :status)
  end
  #taskモデルの中のそれぞれのカラムを使用する
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to root_url
    else
      flash[:success] = 'ユーザ登録に失敗しました'
      render :new
    end
  end
  #@user=User.new(user_params)はparams[:task]でも良いがセキュリティとしてストロングパラメーターしよう


  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  #セキュリティーuserモデルのデータの中のカラムであるということを示す

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  #user.id = session[:user_id]のユーザー（ログイン中の）をインスタンスとして定義
  #ログインしているユーザーのインスタンス, ログインしていなければnilを返す

  def logged_in?
    !!current_user
  end
  #ログイン指定たらtrue, していなければfalse
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-info">
    <a class="navbar-brand" href="/">Tasklist</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '新規登録', new_user_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="ja">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= form_with(model: task, local: true) do |f| %>
     <% if task.errors.any? %>
      <div id="error_explanation">
        <% task.errors.full_messages.each do |tsk| %>
          <ul>
            <li><%= tsk %></li>
          </ul>
        <% end %>
      </div>
      <% end %>
      <div class="form-group">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :status, '状況' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      <%= f.submit '投稿', class: 'btn btn-info' %>
    <% end %>
  </div>
  <div class="col-3 mt-3">
    <%= link_to '一覧に戻る', tasks_path, class: 'btn btn-info' %>
  </div>
</div>

app/views/tasks/_tasks.html.erb
<ul class="list-unstyled">
  <% tasks.each do |task| %>
    <li class="card">
      <div class="card-body">
        <h4 class="card-title card-dark">ユーザ名：<%= task.user.name %></h4>
        <h6 class="card-subtitle text-muted">投稿時間：<%= task.created_at %></h6>
        <h5 class="card-text card-dark">状況：<%= task.status %></h5>
        <h5 class="card-text card-dark">タスク：<%= link_to task.content, task_path(task) %></h5>
      </div>
    </li>
  <% end %>
</ul>
<%= paginate @tasks %>

app/views/tasks/edit.html.erb
<h1>id:<%= @task.id %>のタスク編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= render 'tasks/tasks', tasks: @tasks %>
<%= link_to '新規タスクの投稿', new_task_path, class: 'btn btn-info' %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h5>
  タスク詳細ページ
</h5>
<p>
  進行状況 : <%= @task.status %>
</p>
<p>
  タスク詳細 : <%= @task.content %>
</p>
<div class="row">
<%= link_to 'タスク一覧に戻る', tasks_path, class: 'btn btn-info mr-2' %>
<% if current_user.id == @task.user_id %>
  <%= link_to 'このタスクを編集する', edit_task_path(@task), class: 'btn btn-info mr-2' %>
  <%= link_to 'このタスクを削除する', @task, method: :delete, data: {confirm: '本当に削除してもよろしいですか？'}, class: 'btn btn-info' %>
<% end %>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規作成</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %> 
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'もう一度入力してください' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>